name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libbz2-dev \
            libffi-dev \
            liblzma-dev \
            libsqlite3-dev \
            libssl-dev

      - name: Install Android SDK and Build Tools
        run: |
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk
          chmod -R 777 /home/runner/.buildozer
          cd /home/runner/.buildozer/android/platform/android-sdk
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          mkdir -p cmdline-tools
          unzip sdk-tools.zip -d cmdline-tools
          if [ -d cmdline-tools/cmdline-tools ]; then
            mv cmdline-tools/cmdline-tools cmdline-tools/latest
          else
            mv cmdline-tools/tools cmdline-tools/latest
          fi
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=/home/runner/.buildozer/android/platform/android-sdk "build-tools;34.0.0" "platforms;android-34"

      - name: Install Buildozer and dependencies
        run: |
