name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip openjdk-17-jdk \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libjpeg-dev libfreetype6-dev \
            build-essential autoconf libtool pkg-config zlib1g-dev \
            python3-pip git

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython virtualenv
          pip install buildozer

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
