name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libbz2-dev \
            libffi-dev \
            liblzma-dev \
            libsqlite3-dev \
            libssl-dev

      - name: Install Android SDK and Build Tools
        run: |
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk
          chmod -R 777 /home/runner/.buildozer
          cd /home/runner/.buildozer/android/platform/android-sdk
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          mkdir -p cmdline-tools
          unzip sdk-tools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=/home/runner/.buildozer/android/platform/android-sdk "build-tools;34.0.0" "platforms;android-34"

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33 virtualenv

      - name: Verify buildozer.spec
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          else
            echo "Using existing buildozer.spec file"
          fi

      - name: Build APK
        run: buildozer -v android debug
        env:
          P4A_RELEASE_KEYSTORE: ${{ secrets.P4A_RELEASE_KEYSTORE }}
          P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
          P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}
          P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kisaan-app-apk
          path: bin/*.apk
