name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libbz2-dev \
            libffi-dev \
            liblzma-dev \
            libsqlite3-dev \
            libssl-dev

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33 virtualenv

      - name: Install Android Command Line Tools
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d ~/.android/cmdline-tools
          mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest
          echo 'export PATH=$PATH:~/.android/cmdline-tools/latest/bin' >> $GITHUB_ENV

      - name: Install Android SDK components
        run: |
          yes | ~/.android/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          echo 'export PATH=$PATH:~/.android/cmdline-tools/latest/platform-tools' >> $GITHUB_ENV
          echo 'export PATH=$PATH:~/.android/cmdline-tools/latest/build-tools/34.0.0' >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer -v android debug
        env:
          P4A_RELEASE_KEYSTORE: ${{ secrets.P4A_RELEASE_KEYSTORE }}
          P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
          P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}
          P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}
          ANDROID_SDK_ROOT: ~/.android/cmdline-tools

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kisaan-app-apk
          path: bin/*.apk
