on:

  push:

    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4

      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33"

      - name: Build APK

        uses: digreatbrian/buildozer-action@v2

        with:

          python-version: 3.11

          buildozer-cmd: buildozer -v android debug

      - name: Upload artifacts

        uses: actions/upload-artifact@v4

        with:

          name: package

          path: ./bin/*.apk
